language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key: !binary |-
    AwMDAwM=
  app: vast-sierra-47463
  on:
    repo: sobhit000/hot-or-cold-challenge
